cassandra:
  image: cassandra:2.2.13
  restart: always
  ports:
    - 7000:7000
    - 7001:7001
    - 7199:7199
    - 9042:9042
    - 9160:9160
django1:
  image: somendra11/minimal-django1.5:applying-docker
  restart: always
  ports:
    - 9032:8000
    - 9033:8001
    - 9080:80
    - 9090:443
  extra_hosts:
    - "cassy:127.0.0.1" # cassandra machine ip
    - "localhost:127.0.0.1" # apache machine ip
  volumes:
    - .:/home/app
  command: ["python", "/home/app/manage.py", "sync_cassandra"]
  command: ["httpd", "-k", "start", "-DFOREGROUND"]
